language: python
python:
    - 2.7
    # - 3.3
# TODO: What about yum (rpm) or apt (deb) binaries and C code like BLAS and lapack?
# command to install dependencies
before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/miniconda/bin:$PATH
  - conda update --yes conda
  # The next couple lines fix a crash with multiprocessing on Travis and are not specific to using Miniconda
  - sudo rm -rf /dev/shm
  - sudo ln -s /run/shm /dev/shm
# before_install:
#     - sudo apt-get install -qq libatlas-base-dev gfortran python-numpy python-scipy
#     - "pip install setuptools==3.6"
install:
  - conda install --yes python=$TRAVIS_PYTHON_VERSION atlas numpy scipy matplotlib nose dateutil pandas statsmodels
  # # Coverage packages are on Dan's binstar channel
  # - conda install --yes -c dan_blanchard python-coveralls nose-cov
  - python setup.py install
  - pip freeze
  # - "pip install -r requirements/travis.txt"
  - pip install .
  - pip freeze
  - "conda install ."
  - "pip freeze"
# shell command run tests
script: 
  - "python pug/ann/tests.py"
# build notifications
notifications:
  email:
    - admin@totalgood.com


 
# # Setup anaconda
# before_install:
#   - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
#   - chmod +x miniconda.sh
#   - ./miniconda.sh -b
#   - export PATH=/home/travis/miniconda/bin:$PATH
#   - conda update --yes conda
#   # The next couple lines fix a crash with multiprocessing on Travis and are not specific to using Miniconda
#   - sudo rm -rf /dev/shm
#   - sudo ln -s /run/shm /dev/shm
# # Install packages
# install:
#   - conda install --yes python=$TRAVIS_PYTHON_VERSION atlas numpy scipy matplotlib nose dateutil pandas statsmodels
#   # Coverage packages are on my binstar channel
#   - conda install --yes -c dan_blanchard python-coveralls nose-cov
#   - python setup.py install
 
# # Run test
# script:
#   - nosetests --with-cov --cov YOUR_PACKAGE_NAME_HERE --cov-config .coveragerc --logging-level=INFO
 
# # Calculate coverage
# after_success:
#   - coveralls --config_file .coveragerc
