language: python
python:
    - 2.7
    # - 3.3
# TODO: What about yum (rpm) or apt (deb) binaries and C code like BLAS and lapack?
# command to install dependencies
before_install:
  - sudo apt-get install gfortran-4.6
  - sudo pip install --upgrade pip
  - sudo pip install --upgrade setuptools
  - sudo pip install --upgrade virtualenv
  - sudo apt-get install python-scipy libatlas-base-dev 
  # - pip install setuptools==14.3.1
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/miniconda/bin:$PATH
  - conda update --yes conda
  - conda install numpy==1.9.2
  - conda install scipy==0.15.1
  - conda install pyparsing==2.0.3
  - pip install -r requirements/travis.txt
  # The next couple lines fix a crash with multiprocessing on Travis and are not specific to using Miniconda
  # - sudo rm -rf /dev/shm
  # - sudo ln -s /run/shm /dev/shm
install:
  - conda install --yes python=$TRAVIS_PYTHON_VERSION atlas numpy scipy matplotlib nose dateutil pandas statsmodels
  # # Coverage packages are on Dan's binstar channel
  # - conda install --yes -c dan_blanchard python-coveralls nose-cov
  - pip install pug-nlp==0.0.13
  - python setup.py install
  - pip freeze
  # - "pip install -r requirements/travis.txt"
  - pip install .
  - pip freeze
# shell command run tests
script: 
  - "python pug/ann/tests.py"
# build notifications
notifications:
  email:
    - admin@totalgood.com


 
# # Setup anaconda
# before_install:
#   - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
#   - chmod +x miniconda.sh
#   - ./miniconda.sh -b
#   - export PATH=/home/travis/miniconda/bin:$PATH
#   - conda update --yes conda
#   # The next couple lines fix a crash with multiprocessing on Travis and are not specific to using Miniconda
#   - sudo rm -rf /dev/shm
#   - sudo ln -s /run/shm /dev/shm
# # Install packages
# install:
#   - conda install --yes python=$TRAVIS_PYTHON_VERSION atlas numpy scipy matplotlib nose dateutil pandas statsmodels
#   # Coverage packages are on my binstar channel
#   - conda install --yes -c dan_blanchard python-coveralls nose-cov
#   - python setup.py install
 
# # Run test
# script:
#   - nosetests --with-cov --cov YOUR_PACKAGE_NAME_HERE --cov-config .coveragerc --logging-level=INFO
 
# # Calculate coverage
# after_success:
#   - coveralls --config_file .coveragerc
