language: python
python:
  - "2.7"
# TODO: What about yum (rpm) or apt (deb) binaries and C code like BLAS and lapack?
# command to install dependencies
before_install:
    - sudo apt-get install -qq libatlas-base-dev gfortran python-numpy python-scipy
    - "pip install setuptools==3.6"
install:
    - "pip install -r requirements/travis.txt"
    - "pip install ."
# shell command run tests
script: 
    - "python pug/ann/tests.py"
# build notifications
notifications:
  email:
    - admin@totalgood.com
